small doc changes
obscuronet/go-obscuro pull request #1547
Opened 2023-09-22 11:55 UTC by tudor-malene

### Why this change is needed

Improve docs and add security warning

2023-09-22 17:49 UTC, CaisManai commented on docs/index.md
> +Obscuro hyper-scales and encrypts Ethereum. No SDKs, 100% EVM.
Maybe don't mention "no SDKS", for some reason it triggers people (like at the workshop).
Either way, add 100% Solidity too as this is one of our key USPs (no new languages to learn)

2023-09-22 17:50 UTC, CaisManai requested changes
See comment

2023-09-25 08:25 UTC, tudor-malene commented
@CaisManai , back to you.
Pls approve , and Jobin will take the content from here for the revamp

2023-09-25 08:27 UTC, CaisManai approved these changes

2023-09-25 08:29 UTC, merged