genesis production does not need a known block in the enclave
obscuronet/go-obscuro pull request #207
Opened 2022-05-27 15:27 UTC by otherview

Why is this needed
- Will break node bootstrap

2022-05-30 08:11 UTC, tudor-malene commented
> Why is this needed
> 
> * Will break node bootstrap from network. As this assumes the block is already known by the enclave.

I think this assumption still holds even when bootstrapping from network. The obscuro block history has to start from the block where the management contract was deployed (as we have to process deposits from there).
The genesis rollup will be created on a subsequent block

2022-05-30 08:11 UTC, tudor-malene requested changes
comment above

2022-05-30 10:07 UTC, otherview commented
From what I can tell, the Enclave does not need to process blocks if it does not have the Secret Network Key.

The only case the Enclave needs to process blocks BEFORE having the Secret Key is: When the Genesis Rollup is created.
But only the Genesis Node creates the Genesis Rollup, so I think this is fine to trust on the hash that's provided.

That's my logic, wdyt @tudor-malene  ?

In addition to this, we should feed in the Contract Tx so that the genesis node pulls the tx block and uses it as the l1 proof. 
But maybe that can go on a different PR ?

2022-10-31 13:47 UTC, otherview commented
Deprecated in relation with tasks under https://github.com/obscuronet/obscuro-internal/labels/T5

2022-10-31 13:47 UTC, closed without merging